-- ============================================================================
-- HiAlice Phase 2 Migration — Book Context & AI Feedback Scores
-- Project: HiAlice - Interactive English Reading App for Children (6-13)
-- Version: 3.0
-- Date: 2026-03-10
-- Depends on: 002_phase1_enhancement.sql
-- ============================================================================
-- This migration adds:
--   1. Book context columns for AI-personalized question generation
--      (synopsis, key_themes, emotional_keywords, key_characters, moral_lesson)
--   2. AI feedback + emotion/creativity/depth scores on sessions table
--   3. Seed data: synopsis + context for the three default sample books
-- ============================================================================

-- ============================================================================
-- 1. BOOK CONTEXT COLUMNS
-- ============================================================================
-- These fields are consumed by the AI engine (prompts.js) to generate
-- book-specific, emotion-eliciting Socratic questions instead of generic ones.

ALTER TABLE books ADD COLUMN IF NOT EXISTS synopsis            TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS key_themes          TEXT[];
ALTER TABLE books ADD COLUMN IF NOT EXISTS emotional_keywords  TEXT[];
ALTER TABLE books ADD COLUMN IF NOT EXISTS key_characters      JSONB DEFAULT '[]'::jsonb;
ALTER TABLE books ADD COLUMN IF NOT EXISTS moral_lesson        TEXT;

-- ============================================================================
-- 2. AI FEEDBACK + DIMENSIONAL SCORES ON SESSIONS
-- ============================================================================
-- ai_feedback    — personalized end-of-session text generated by HiAlice
-- emotion_score  — how well the student connected emotionally (0-100)
-- creativity_score — creative / divergent thinking quality (0-100)
-- depth_score    — analytical depth and elaboration (0-100)

ALTER TABLE sessions ADD COLUMN IF NOT EXISTS ai_feedback      TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS emotion_score    INTEGER DEFAULT 0 CHECK (emotion_score    BETWEEN 0 AND 100);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS creativity_score INTEGER DEFAULT 0 CHECK (creativity_score BETWEEN 0 AND 100);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS depth_score      INTEGER DEFAULT 0 CHECK (depth_score      BETWEEN 0 AND 100);

-- ============================================================================
-- 3. SEED — BOOK CONTEXT DATA
-- ============================================================================
-- Updates the three default sample books seeded in the initial schema.
-- Uses ILIKE so the update is robust to minor title-casing differences.

-- The Very Hungry Caterpillar — Eric Carle
UPDATE books SET
  synopsis           = 'A tiny caterpillar eats through a variety of foods before transforming into a beautiful butterfly.',
  key_themes         = ARRAY['transformation', 'growth', 'perseverance', 'nature'],
  emotional_keywords = ARRAY['hungry', 'full', 'tired', 'beautiful', 'amazing'],
  key_characters     = '[{"name": "The Caterpillar", "trait": "hungry and determined"}]'::jsonb,
  moral_lesson       = 'Growth takes time and patience — big changes happen slowly but beautifully'
WHERE title ILIKE '%hungry caterpillar%';

-- Charlotte''s Web — E.B. White
UPDATE books SET
  synopsis           = 'A young girl named Charlotte is best friends with Wilbur the pig. When Wilbur faces a terrible fate, Charlotte weaves words into her web to save him.',
  key_themes         = ARRAY['friendship', 'sacrifice', 'loyalty', 'mortality'],
  emotional_keywords = ARRAY['friendship', 'brave', 'sad', 'hopeful', 'grateful'],
  key_characters     = '[{"name": "Charlotte", "trait": "wise and selfless"}, {"name": "Wilbur", "trait": "innocent and loving"}]'::jsonb,
  moral_lesson       = 'True friendship means giving your best even when it costs you everything'
WHERE title ILIKE '%charlotte%';

-- Harry Potter and the Sorcerer''s Stone — J.K. Rowling
UPDATE books SET
  synopsis           = 'Harry Potter discovers he is a wizard and enters Hogwarts School of Witchcraft and Wizardry, where he makes friends and faces the dark wizard who killed his parents.',
  key_themes         = ARRAY['courage', 'friendship', 'identity', 'good vs evil'],
  emotional_keywords = ARRAY['brave', 'scared', 'excited', 'belonging', 'magical'],
  key_characters     = '[{"name": "Harry", "trait": "brave and curious"}, {"name": "Hermione", "trait": "clever and loyal"}, {"name": "Ron", "trait": "funny and faithful"}]'::jsonb,
  moral_lesson       = 'Love and friendship are the most powerful magic of all'
WHERE title ILIKE '%harry potter%' AND title ILIKE '%sorcerer%';

-- ============================================================================
-- 4. INDEXES
-- ============================================================================
-- GIN index on key_themes for future array-contains searches
-- (e.g. find all books tagged 'friendship')
CREATE INDEX IF NOT EXISTS idx_books_key_themes
  ON books USING GIN (key_themes);

-- Partial index — only index sessions that have ai_feedback generated
CREATE INDEX IF NOT EXISTS idx_sessions_ai_feedback
  ON sessions (id)
  WHERE ai_feedback IS NOT NULL;
