export const MOCK_BOOK_CATALOG = [
  {
    id: 'mock-book-001',
    title: 'The Very Hungry Caterpillar',
    author: 'Eric Carle',
    level: 'Beginner',
    genre: 'Picture Book',
    cover: '🐛',
    coverEmoji: '🐛',
    description: 'A tiny caterpillar nibbles through colorful foods and transforms into a butterfly.',
    synopsis: 'A hungry caterpillar explores food, learns patience, and grows into something beautiful.',
    rating: 4.8,
    reviewCount: 2340,
    badge: 'Bestseller',
    ageRange: 'Ages 3-6',
    gradeLevel: 'Grade Pre-K',
    progress: 0,
    curiosityHook: 'Count the foods, spot the colors, and guess when the butterfly will appear.',
    animationStyle: 'playful paper-cut motion with drifting fruit and a smiling caterpillar',
    searchTokens: ['food', 'butterfly', 'change', 'growth', 'nature', 'colorful', 'animal'],
    discoveryThemes: ['Transformation', 'Nature', 'Food Adventure'],
    moods: ['Curious', 'Gentle', 'Bright'],
  },
  {
    id: 'mock-book-002',
    title: 'Where the Wild Things Are',
    author: 'Maurice Sendak',
    level: 'Beginner',
    genre: 'Picture Book',
    cover: '👹',
    coverEmoji: '👹',
    description: 'Max sails to a wild island where imagination becomes a roaring adventure.',
    synopsis: 'A child explores big feelings through imagination and returns home feeling understood.',
    rating: 4.7,
    reviewCount: 1890,
    badge: 'Award Winner',
    ageRange: 'Ages 4-8',
    gradeLevel: 'Grade K-2',
    progress: 0,
    curiosityHook: 'Can you hear the wild rumpus and imagine what Max says to the monsters?',
    animationStyle: 'moonlit jungle adventure with glowing eyes, boats, and swaying trees',
    searchTokens: ['monster', 'island', 'adventure', 'feelings', 'imagination', 'night'],
    discoveryThemes: ['Imagination', 'Feelings', 'Adventure'],
    moods: ['Brave', 'Dreamy', 'Wild'],
  },
  {
    id: 'mock-book-003',
    title: "Charlotte's Web",
    author: 'E.B. White',
    level: 'Intermediate',
    genre: 'Chapter Book',
    cover: '🕷️',
    coverEmoji: '🕷️',
    description: 'A pig and a spider form a friendship that changes a whole farm.',
    synopsis: 'Wilbur and Charlotte show how friendship, kindness, and sacrifice can save someone.',
    rating: 4.9,
    reviewCount: 3120,
    badge: 'Award Winner',
    ageRange: 'Ages 7-10',
    gradeLevel: 'Grade 2-4',
    progress: 35,
    curiosityHook: 'Watch words appear in the web and guess how the farm will react.',
    animationStyle: 'warm barn light, glowing spider silk, and cozy farm friends',
    searchTokens: ['friendship', 'farm', 'pig', 'spider', 'kindness', 'animals'],
    discoveryThemes: ['Friendship', 'Empathy', 'Farm Life'],
    moods: ['Tender', 'Thoughtful', 'Hopeful'],
  },
  {
    id: 'mock-book-004',
    title: 'The Lion, the Witch and the Wardrobe',
    author: 'C.S. Lewis',
    level: 'Intermediate',
    genre: 'Fantasy',
    cover: '🦁',
    coverEmoji: '🦁',
    description: 'A wardrobe opens into a snowy world filled with courage, magic, and destiny.',
    synopsis: 'Four siblings enter Narnia and learn bravery, forgiveness, and sacrifice.',
    rating: 4.8,
    reviewCount: 2780,
    badge: 'Bestseller',
    ageRange: 'Ages 8-12',
    gradeLevel: 'Grade 3-5',
    progress: 0,
    curiosityHook: 'Open the wardrobe door and step into a snow-covered forest with hidden secrets.',
    animationStyle: 'sparkling snow fantasy with lantern glow, magical creatures, and golden light',
    searchTokens: ['fantasy', 'wardrobe', 'snow', 'magic', 'lion', 'adventure'],
    discoveryThemes: ['Fantasy World', 'Courage', 'Magic'],
    moods: ['Epic', 'Wonder', 'Heroic'],
  },
  {
    id: 'mock-book-005',
    title: 'Magic Tree House: Dinosaurs Before Dark',
    author: 'Mary Pope Osborne',
    level: 'Intermediate',
    genre: 'Adventure',
    cover: '🌳',
    coverEmoji: '🌳',
    description: 'A tree house whisks Jack and Annie into the age of dinosaurs.',
    synopsis: 'Siblings travel through time and learn curiosity, courage, and teamwork.',
    rating: 4.6,
    reviewCount: 1560,
    badge: 'Popular',
    ageRange: 'Ages 6-9',
    gradeLevel: 'Grade 1-3',
    progress: 60,
    curiosityHook: 'Climb into the tree house and listen for giant footsteps in the jungle.',
    animationStyle: 'time-travel jungle chase with glowing maps and playful dinosaur movement',
    searchTokens: ['dinosaur', 'tree house', 'time travel', 'jungle', 'siblings', 'mystery'],
    discoveryThemes: ['Time Travel', 'Adventure', 'Discovery'],
    moods: ['Energetic', 'Adventurous', 'Playful'],
  },
  {
    id: 'mock-book-006',
    title: 'A Wrinkle in Time',
    author: "Madeleine L'Engle",
    level: 'Advanced',
    genre: 'Science Fiction',
    cover: '⭐',
    coverEmoji: '⭐',
    description: 'Meg travels across space and time to find her father and discover her courage.',
    synopsis: 'A family rescue mission becomes a story about love, bravery, and identity.',
    rating: 4.5,
    reviewCount: 1980,
    badge: 'Award Winner',
    ageRange: 'Ages 10-14',
    gradeLevel: 'Grade 5-8',
    progress: 0,
    curiosityHook: 'Fold space like a map and imagine what a tesseract feels like.',
    animationStyle: 'cosmic nebula voyage with glowing constellations and surreal portals',
    searchTokens: ['space', 'science fiction', 'family', 'rescue', 'stars', 'portal'],
    discoveryThemes: ['Cosmic Adventure', 'Family', 'Resilience'],
    moods: ['Cosmic', 'Mysterious', 'Bold'],
  },
  {
    id: 'mock-book-007',
    title: 'Inkheart',
    author: 'Cornelia Funke',
    level: 'Advanced',
    genre: 'Fantasy',
    cover: '📖',
    coverEmoji: '📖',
    description: 'A girl discovers that stories can come to life when read aloud.',
    synopsis: 'Books become portals, and reading becomes a superpower.',
    rating: 4.4,
    reviewCount: 890,
    ageRange: 'Ages 10-14',
    gradeLevel: 'Grade 5-7',
    progress: 0,
    curiosityHook: 'What if a villain stepped out of the page right into your room?',
    animationStyle: 'ink swirls, floating letters, and cinematic storyworld portals',
    searchTokens: ['book magic', 'reading aloud', 'characters', 'portal', 'ink', 'story'],
    discoveryThemes: ['Book Magic', 'Adventure', 'Imagination'],
    moods: ['Magical', 'Suspenseful', 'Curious'],
  },
  {
    id: 'mock-book-008',
    title: 'The Book Thief',
    author: 'Markus Zusak',
    level: 'Advanced',
    genre: 'Historical Fiction',
    cover: '📚',
    coverEmoji: '📚',
    description: 'A girl finds comfort and courage in books during a difficult time.',
    synopsis: 'Stories become shelter, memory, and hope in a world shaped by war.',
    rating: 4.7,
    reviewCount: 2150,
    badge: 'Bestseller',
    ageRange: 'Ages 12+',
    gradeLevel: 'Grade 6-8',
    progress: 15,
    curiosityHook: 'Why do some stories become a safe place when life feels scary?',
    animationStyle: 'soft cinematic lighting, drifting paper pages, and reflective scenes',
    searchTokens: ['history', 'war', 'books', 'hope', 'courage', 'memory'],
    discoveryThemes: ['Hope', 'History', 'Words Matter'],
    moods: ['Reflective', 'Deep', 'Hopeful'],
  },
  {
    id: 'mock-book-009',
    title: 'Winnie-the-Pooh',
    author: 'A.A. Milne',
    level: 'Beginner',
    genre: 'Picture Book',
    cover: '🐻',
    coverEmoji: '🐻',
    description: 'Pooh and his friends turn small forest moments into warm adventures.',
    synopsis: 'A gentle collection of friendship stories full of humor and heart.',
    rating: 4.8,
    reviewCount: 3450,
    badge: 'Popular',
    ageRange: 'Ages 3-7',
    gradeLevel: 'Grade Pre-K-1',
    progress: 0,
    curiosityHook: 'Follow Pooh into the Hundred Acre Wood and look for honey, balloons, and giggles.',
    animationStyle: 'soft watercolor forest with bouncing bees and cozy storybook motion',
    searchTokens: ['bear', 'friendship', 'forest', 'honey', 'gentle', 'animals'],
    discoveryThemes: ['Friendship', 'Forest Life', 'Comfort'],
    moods: ['Cozy', 'Gentle', 'Happy'],
  },
  {
    id: 'mock-book-010',
    title: 'Matilda',
    author: 'Roald Dahl',
    level: 'Intermediate',
    genre: 'Fiction',
    cover: '👧',
    coverEmoji: '👧',
    description: 'A brilliant girl discovers the power of books, courage, and her own voice.',
    synopsis: 'Matilda faces unfair adults and learns to stand up for herself and others.',
    rating: 4.7,
    reviewCount: 2670,
    badge: 'Popular',
    ageRange: 'Ages 7-11',
    gradeLevel: 'Grade 2-5',
    progress: 0,
    curiosityHook: 'What happens when a quiet reader becomes the smartest person in the room?',
    animationStyle: 'storybook classroom magic with floating books and sparkling telekinesis',
    searchTokens: ['school', 'girl hero', 'books', 'magic', 'smart', 'funny'],
    discoveryThemes: ['Empowerment', 'School Story', 'Magic'],
    moods: ['Confident', 'Funny', 'Smart'],
  },
];

export function normalizeMockBook(book) {
  return {
    ...book,
    cover_emoji: book.cover_emoji || book.coverEmoji || book.cover,
  };
}

export function getBookSearchText(book) {
  return [
    book.title,
    book.author,
    book.genre,
    book.description,
    book.synopsis,
    book.curiosityHook,
    ...(book.searchTokens || []),
    ...(book.discoveryThemes || []),
    ...(book.moods || []),
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();
}
